### ISSUE TITLE
@babel/polyfill 7.4.0+ has been deprecated

### ISSUE THREAD

**Issue by xg-wang** [babel/ember-cli-babel#298]
```
warning ember-cli-babel > @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
package has been deprecated in favor of directly
including core-js/stable (to polyfill ECMAScript
features) and regenerator-runtime/runtime
(needed to use transpiled generator functions):

  > import "core-js/stable";
  > import "regenerator-runtime/runtime";
```

**Comment by rwjblue** [comment]
Thanks for reporting. Definitely need to get this fixed.

**Comment by patocallaghan** [comment]
@rwjblue I've also just been hit by this issue in our app. `Object.fromEntries` is not polyfilled by `@babel/polyfill`. This is because `@babel/polyfill` (now deprecated) ships with core-js 2.x (2.x is deprecated) and [`Object.fromEntries` only ships from 3.x](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#what-changed-in-core-js3).

I'm happy to try and put together a PR if it's just a matter of switching out dependendencies, and tweaking the build pipeline?

**Comment by rwjblue** [comment]
@patocallaghan - I haven't really dug into this so I'm not sure if that is all that we need to do, but it seems reasonable to me and help (even just researching) is absolutely welcome.

**Comment by patocallaghan** [comment]
Okay thanks, I'll see if I can dig in at some stage this week

**Comment by SergeAstapov** [comment]
Logged https://github.com/babel/broccoli-babel-transpiler/issues/197 as `@babel/polyfill` is used by `ember-cli-babel` and `broccoli-babel-transpiler`

**Comment by rwjblue** [comment]
https://github.com/babel/broccoli-babel-transpiler/pull/191 removed the polyfill from broccoli-babel-transpiler already, just hasn't been released yet (it'll be 8.0.0).

**Comment by SergeAstapov** [comment]
great news @rwjblue! sorry for churn, didn't check latest `master`

**Comment by SergeAstapov** [comment]
Now this is being blocked by babel/broccoli-babel-transpiler#200

**Comment by cincodenada** [comment]
Checking in here, it looks like the blocker has been merged now 🥳

**Comment by john-griffin** [comment]
What was the outcome of this? How do we restore the `Object.fromEntries` polyfill?

**Comment by bertdeblock** [comment]
Going to close this as polyfill support was removed in v8.
