### ISSUE TITLE
Implement preset-modules for modern browsers

### ISSUE THREAD

**Issue by Exelord** [babel/ember-cli-babel#308]
@rwjblue What do think about implementing [preset-modules](https://github.com/babel/preset-modules) and generate output files for "module" and "nomodule" browsers?

**Comment by rwjblue** [comment]
I think using preset-modules would be straight forward with the current ember-cli-babel design (you'd opt out of preset env, and add preset modules), but making ember-cli emit both files is a bit of a larger task. Specifically prior to using something like Embroider, each addon is compiled independently down to the specified set of targets. This means that in order to allow emitting both modules and no-modules bundles we'd need to do some significant refactors to ember-cli's current build pipeline.

**Comment by Exelord** [comment]
:/ yeah I meant the second approach to generate fo sets of file. This could be a great improvement and could close the topic of browsers support tradeoff.

Let's hope maybe in the future this will be possible.
