### ISSUE TITLE
Package no longer installs on Node 6/8

### ISSUE THREAD

**Issue by Turbo87** [babel/ember-cli-babel#326]
`babel-plugin-ember-data-packages-polyfill` specifies `10.* || >= 12.*` as its Node support, which is incompatible with `ember-cli-babel` still supporting Node 6 and 8.

/cc @rwjblue @runspired

**Comment by Turbo87** [comment]
Example CI failure: https://travis-ci.com/simplabs/ember-promise-modals/jobs/284724222

**Comment by rwjblue** [comment]
Hmm, ember-cli-babel's own CI passes on Node 6 🤔

**Comment by rwjblue** [comment]
(I confirmed that it was running properly before merging)

**Comment by Turbo87** [comment]
yep, but it's using `--ignore-engines` 😞

**Comment by sandydoo** [comment]
Also the ember-cli default for both apps and addons is `"node": "8.* || >= 10.*"` and the node version for travis is also set to 8, so it's easy to stumble on this just by religiously upgrading with `ember-cli-update`.

**Comment by xg-wang** [comment]
I'm seeing same error, does `babel-plugin-ember-data-packages-polyfill` only work on node 10+?

**Comment by runspired** [comment]
@xg-wang it should work with more versions than that although the tests may not. The issue is it declares a version in engines that although is the correct version for what we support in the ember ecosystem at the point it was released is not what ember-cli-Babel currently has.

I’m going to see about cutting a version that ensures support for these legacy versions but we should also bump ember-cli-Babel soon

**Comment by runspired** [comment]
https://github.com/ember-data/babel-plugin-ember-data-packages-polyfill/pull/4 will resolve this for the plugin
